name: Build Emulator Binaries

on:
  push:
    branches: ["main", "DotBox"]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libwayland-dev libxkbcommon-dev
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Compile native binary
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Stage windows executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: PixelForge-Win64
          path: ${{github.workspace}}/build/Release/PixelForge.exe

      - name: Stage macos app bundle
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: PixelForge-macOS
          path: ${{github.workspace}}/build/PixelForge.app

      - name: Stage Linux Executable
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: PixelForge-Linux
          path: ${{github.workspace}}/build/PixelForge